Bug/gh724 update parameters values grid
RHEAGROUP/CDP4-IME-Community-Edition pull request #1123
Opened 2022-06-21 09:42 UTC by omaratstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

- Change parameter grid in the grapher into a tree
![image](https://user-images.githubusercontent.com/104059834/174769716-c5743989-400f-46ca-ba59-cf824b59304c.png)

2022-06-21 09:54 UTC, lxatrhea commented on CDP4Composition/ViewModels/CompoundParameterTypeRowViewModel.cs
> +        /// <returns></returns>
missing docs

2022-06-21 09:54 UTC, lxatrhea commented on CDP4Composition/ViewModels/CompoundParameterTypeRowViewModel.cs
> +        /// <returns></returns>
missing docs

2022-06-21 09:55 UTC, lxatrhea commented on CDP4Composition/ViewModels/ParameterRowControlViewModel.cs
> +        public ParameterRowControlViewModel()
missing docs

2022-06-21 09:57 UTC, lxatrhea commented on CDP4Composition/ViewModels/StateDependenceRowViewModel.cs
> +        /// <returns></returns>
missing docs

2022-06-21 09:57 UTC, lxatrhea commented on CDP4Composition/ViewModels/ParameterRowControlViewModel.cs
> +        /// <returns></returns>
missing docs

2022-06-21 11:48 UTC, lxatrhea approved these changes

2022-06-21 12:00 UTC, samatrhea requested changes

2022-06-24 15:46 UTC, alexatrhea approved these changes

2022-06-24 15:48 UTC, merged