Improvement/gh546 improve selected category display behavior in matrix configuration; #546
RHEAGROUP/CDP4-IME-Community-Edition pull request #548
Opened 2020-09-07 11:46 UTC by kamilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

I have changed a little previous merged solution, that concerns this case.
New approach is based on the ReactiveList instead of converter.
New approach listed category with subcategories if checked.

2020-09-07 11:49 UTC, samatrhea requested changes

2020-09-07 11:49 UTC, samatrhea commented on RelationshipMatrix/ViewModels/SourceConfigurationViewModel.cs
> +    using DevExpress.CodeParser;
why is this here?

2020-09-07 11:54 UTC, samatrhea approved these changes

2020-09-08 11:28 UTC, alexatrhea commented on RelationshipMatrix.Tests/ViewModel/RelationshipMatrixViewModelTestFixture.cs
> +            Assert.AreEqual(0, vm.Matrix.Records.Count);
Why did this go down to 0?

2020-09-08 12:56 UTC, alexatrhea approved these changes

2020-09-08 14:37 UTC, merged