Add the save mapping feature; fixes #558
RHEAGROUP/CDP4-IME-Community-Edition pull request #570
Opened 2020-09-14 08:34 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
fixes #558

- Added the save to an ExternalIdentifierMap the result of the mapping functionality.

2020-09-14 09:59 UTC, lxatrhea requested changes

2020-09-14 09:59 UTC, lxatrhea commented on Requirements.Tests/ReqIF/ReqIfImportMappingManagerTestFixture.cs
>  }
newline

2020-09-14 09:59 UTC, lxatrhea commented on Requirements/ReqIFDal/ReqIfImportMappingManager.cs
> +            if (res?.Result != true)
Please use a more discriptive name for `res`, like mappingDialogNavigationResult

2020-09-14 10:20 UTC, lxatrhea approved these changes

2020-09-14 19:22 UTC, alexatrhea approved these changes

2020-09-14 19:28 UTC, samatrhea reviewed
@nathanatrhea i would like to get a demonstration of this, how about tuesday morning at 9:00?

2020-09-15 06:42 UTC, kamilatrhea approved these changes

2020-10-02 11:00 UTC, closed without merging