Feat/gh557 req if repeat an import without having to map again
RHEAGROUP/CDP4-IME-Community-Edition pull request #578
Opened 2020-09-24 11:08 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
fixes #557; fixes #558

[x] Imported requirements mapping get reused and can be modified

2020-09-28 12:15 UTC, lxatrhea requested changes

2020-09-28 12:15 UTC, lxatrhea commented on Requirements/ViewModels/ReqIF/RequirementSpecificationMappingDialogViewModel.cs
> +        /// <summary>                                                                                                                                        = new SpecificationTypeMapConverter(this.r
This line looks strange in the diff view. Looks like a copy/paste at the wrong place.

2020-10-01 08:24 UTC, alexatrhea commented
Is this ready for review?

2020-10-01 10:18 UTC, alexatrhea approved these changes

2020-10-02 07:03 UTC, lxatrhea approved these changes

2020-10-02 10:57 UTC, merged