Finetuning
RHEAGROUP/CDP4-IME-Community-Edition pull request #585
Opened 2020-10-09 15:51 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Finetuning, bugfixing and refactoring sprint 18.

2020-10-12 06:11 UTC, cozminvelciu requested changes

2020-10-12 06:11 UTC, cozminvelciu commented on CDP4Reporting.Tests/DataCollection/DataCollectorStateDependentRowDoubleParameterTestFixture.cs
> +}
Missing newline at end of file.

2020-10-12 06:11 UTC, cozminvelciu commented on CDP4Reporting/DataCollection/DataCollectorCategory.cs
> -        /// <param name="table">
The parameter named "table" is still present in the signature.

2020-10-12 06:11 UTC, cozminvelciu commented on CDP4Reporting/DataCollection/DataCollectorNode.cs
> +        /// If set to true, a new <see cref="T"/> will be created and the cach field <see cref="rowRepresentation"/> will not be set.
Typo: "cach".

2020-10-12 06:11 UTC, cozminvelciu commented on CDP4Reporting/DataCollection/DataCollectorNode.cs
> +        /// Fills the <see cref="DataColumn"/>s with data for properties of an instance of <see cref="T"/> whose <see cref="Type"/> implement <see cref="IDataCollectorStateDependentPerRowParameter"/>
This line is a bit too long, I would suggest splitting it before "implement <see ...".

2020-10-12 09:03 UTC, alexatrhea approved these changes

2020-10-14 07:38 UTC, samatrhea approved these changes
no comment... ah, that was already a comment, nevermind

2020-10-14 07:46 UTC, merged