WIP: Fixes #590, #605 Custom Filtering
RHEAGROUP/CDP4-IME-Community-Edition pull request #607
Opened 2020-11-06 12:23 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Add Custom Filter functionality to all Browsers.

2020-11-09 14:06 UTC, alexatrhea requested changes
Docs missing here and there, for the rest, good.

2020-11-09 14:06 UTC, alexatrhea commented on CDP4Composition/Services/FilterEditorService/ISavedUserPreference.cs
> +    public interface ISavedUserPreference
docs

2020-11-09 14:06 UTC, alexatrhea commented on EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ElementUsageRowViewModel.cs
> +        public new IEnumerable<Category> Category => this.Thing.Category.Union(this.Thing.ElementDefinition.Category).Distinct();
docs

2020-11-09 14:06 UTC, alexatrhea commented on EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/IElementBaseRowViewModel.cs
> +        IEnumerable<Category> Category { get; }
docs

2020-11-09 15:58 UTC, alexatrhea approved these changes

2020-11-10 18:59 UTC, alexatrhea approved these changes

2020-11-12 09:57 UTC, samatrhea approved these changes
some small comments

2020-11-12 09:57 UTC, samatrhea commented on EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ElementBaseRowViewModel.cs
> +        public IEnumerable<Category> Category => this.Thing.Category;
docs

2020-11-16 11:12 UTC, merged