Fixes #123: Refactor PanelNavigationService and open PropertyGrid
RHEAGROUP/CDP4-IME-Community-Edition pull request #644
Opened 2020-12-04 13:23 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Refactor PanelNavigationService and open PropertyGrid

2020-12-04 13:30 UTC, nathanatrhea approved these changes

2020-12-04 13:30 UTC, nathanatrhea commented on CDP4PropertyGrid/ViewModels/PropertyGridViewModel.cs
>  }
New line please

2020-12-04 13:53 UTC, ahmedatrhea approved these changes

2020-12-04 13:59 UTC, alexatrhea approved these changes

2020-12-04 16:00 UTC, samatrhea requested changes

2020-12-07 08:30 UTC, lxatrhea commented on CDP4PropertyGrid/ViewModels/PropertyGridViewModel.cs
> +                    CDPMessageBus.Current.SendMessage(new ViewModelChangeEvent(newVm));
Flow:

- User changes selected item
- BrowserViewModelBase fires SelectedThingChangedEvent
- PropertyGridViewModel listens to SelectedThingChangedEvent
- PropertyGridViewModel creates new ViewModel
- PropertyGridViewModel fires ViewModelChangeEvent
- PanelNavigationService listens to ViewModelChangeEvent
- PanelNavigationService Replaces new ViewModel

2020-12-07 11:05 UTC, samatrhea approved these changes

2020-12-07 16:16 UTC, merged