[WIP] Fixes #691 and #696 parameter to state mapping
RHEAGROUP/CDP4-IME-Community-Edition pull request #705
Opened 2021-01-19 19:11 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Parameter to State Mapping

2021-01-20 07:20 UTC, samatrhea approved these changes
some minor remarks, would be good to get a demo today

2021-01-20 07:20 UTC, samatrhea commented on CDP4ReferenceDataMapper.Tests/packages.config
> +  <package id="MSTest.TestAdapter" version="2.1.1" targetFramework="net452" />
i am surprised this file is here, should these references not be in the .csproj file?

2021-01-20 07:20 UTC, samatrhea commented on CDP4ReferenceDataMapper/Behaviors/MappingCellReadOnlyBehavior.cs
> +    /// Add custom readonly behavior to cells of a <see cref="TreeListView"/>
can you correct the docs, not sure how to read the sentence

2021-01-20 07:20 UTC, samatrhea commented on CDP4ReferenceDataMapper/Converters/MappingRowItemsSourceConverter.cs
> +            throw new NotImplementedException();
please make this a `NotSupportedException`

2021-01-21 10:04 UTC, alexatrhea requested changes
Some minor things. But can you also straight away include the new plugin into the installer?

2021-01-21 11:12 UTC, alexatrhea approved these changes

2021-01-22 12:27 UTC, alexatrhea approved these changes

2021-01-22 12:40 UTC, samatrhea requested changes

2021-01-22 12:40 UTC, samatrhea commented on CDP4Composition/ViewModels/ParameterRowControlViewModel.cs
> +                valueSet = parameterOverride.ValueSet.FirstOrDefault(x => (!this.Parameter.IsOptionDependent || (x.ActualOption == this.ActualOption)));
if a server is returning incomplete data, i think we fail/crash here. Perhaps wrap an exception or go back to SingleOrDefault?

2021-01-22 12:40 UTC, samatrhea commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
>          public object[,] LockArray { get; private set; }
changes to cross-view in this PR?

2021-01-22 12:44 UTC, lxatrhea commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
>          public object[,] LockArray { get; private set; }
no, rebased

2021-01-22 12:52 UTC, merged