WIP: #659 add calculation algorithm for p mean
RHEAGROUP/CDP4-IME-Community-Edition pull request #714
Opened 2021-01-22 15:03 UTC by adrianchivu

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

2021-01-27 11:21 UTC, lxatrhea approved these changes

2021-01-28 15:11 UTC, cozminvelciu requested changes

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +            if (pDutyCycle.StateDependence.ActualState.Count == 0 || pMean.StateDependence.ActualState.Count == 0)
This check is not strong enough, there's no need to compare the state counts, it should be enough that both have the same StateDependence (of type ActualFiniteStateList): `pDutyCycle.StateDependence == pMean.StateDependence`.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        /// <param name="parameters"></param>
Missing XML docs.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        /// <returns>True if all power related parameters are present, False otherwise</returns>
All XML docs should be on separate lines from the tags for consistency.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        public static double? ComputeCalculation(string standByValue, string onValue, string dutyCycleValue, string redundancyScheme, string redundancyType, string redundancyK, string redundancyN)
Missing XML docs.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        public static double? ComputeCalculation(string standByValue, string onValue, string dutyCycleValue, string redundancyScheme, string redundancyType, string redundancyK, string redundancyN)
Split each parameter on a new line.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        /// NOTE: not sure about this value
Let's make sure about this. I will also look into it.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        /// NOTE: not sure about this value
Let's make sure about this. I will also look into it.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +            double.TryParse(standByValue, NumberStyles.Any, CultureInfo.InvariantCulture, out var pStandByValue);
Should we check the returned boolean, so that if the parsing failed we handle it properly? We should probably just return null in that case.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +        public static double? ComputeCalculation(string standByValue, string onValue, string dutyCycleValue, string redundancyScheme, string redundancyType, string redundancyK, string redundancyN)
Rename to `ComputePMean`.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +            for (var i = 0; i < pDutyCycleIndexes.Count(); i++)
This assumes that for pMean and pDutyCycle values each index corresponds to the same option/state. Which could technically be false, as there's no guarantee about the order of these.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-01-28 15:11 UTC, cozminvelciu commented on CDP4CrossViewEditor.Tests/Assemblers/CrossviewPMeanArrayAssemblerTestFixture.cs
> +            // The that power related parameters are present into the header
Typo in comment "the that power related..."?

Given that this is repeated to many times, I would just remove this comment completely.

2021-02-04 13:06 UTC, samatrhea requested changes

2021-02-04 13:06 UTC, samatrhea commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +                                    int>>>>>>();
these are git merge problem markers that should not be here. Please fix

2021-02-04 13:06 UTC, samatrhea commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +            if (pMeanIndexes.Length != pDutyCycleIndexes.Length)
there are IComparer implementations in Composition that can be reused or can serve as example

2021-02-08 13:22 UTC, cozminvelciu commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +            var rSchemeIndex = indexes.FirstOrDefault(p => p.Item1.Equals("redundancy.scheme", StringComparison.InvariantCultureIgnoreCase)).Item2;
I also removed the hardcoded strings in `CrossviewSheetPMeanUtilities` and replaced them with constants.

2021-02-08 13:44 UTC, cozminvelciu requested changes

2021-02-08 13:44 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +            if (pDutyCycle.IsOptionDependent != pMean.IsOptionDependent)
Option dependency needs to be taken into account for all parameters, not just "p_duty_cyc" and "p_mean".

2021-02-09 07:32 UTC, cozminvelciu reviewed
One more thing that would be nice to add: highlight computed values differently. Maybe lock them?

2021-02-09 07:33 UTC, cozminvelciu reviewed
One last thing that would be nice to add: highlight computed values differently. Maybe lock them?

2021-02-09 08:12 UTC, cozminvelciu approved these changes

2021-02-09 09:41 UTC, cozminvelciu commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +            var indexes = CrossviewSheetConstants.PowerParameters.Select(p => this.GetContentColumnsIndexes(calculationParameters, p)).SelectMany(x => x).ToList();
Fixed as of `aae9b12`.

2021-02-09 09:41 UTC, cozminvelciu commented on CDP4CrossViewEditor/Assemblers/CrossviewArrayAssembler.cs
> +            if (!isCalculationPossible)
Fixed as of `aae9b12`.

2021-02-09 09:41 UTC, cozminvelciu commented on CDP4CrossViewEditor/Generator/CrossviewSheetPMeanUtilities.cs
> +            if (pDutyCycle.IsOptionDependent != pMean.IsOptionDependent)
Fixed as of `aae9b12`.

2021-02-09 09:50 UTC, samatrhea approved these changes

2021-02-09 11:45 UTC, cozminvelciu commented
The automatic merge made by GitHub messed up this branch, I'll try to fix it manually.

2021-02-09 12:45 UTC, merged