#710 Protect fixed columns and header cells
RHEAGROUP/CDP4-IME-Community-Edition pull request #716
Opened 2021-01-25 23:09 UTC by adrianchivu

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [X] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [X] I have provided test coverage for my change (where applicable)

### Description

2021-01-26 08:57 UTC, alexatrhea approved these changes

2021-01-27 15:35 UTC, cozminvelciu requested changes
Will review after [parent PR](#684) is merged, as for now the diff is inconclusive. Being forced into sequential reviews and merges (instead of handling each issue separately) is one of the disadvantages of having multiple branches based on one another.

2021-01-28 10:09 UTC, cozminvelciu requested changes
I will do the changes.

2021-01-28 10:11 UTC, cozminvelciu approved these changes
Approving my own changes; @alexatrhea, please take another look over these as I have fixed off-by-one errors in all Excel sheets generations.

2021-01-29 14:12 UTC, alexatrhea approved these changes

2021-01-29 14:13 UTC, merged