[WIP] #712 Add crossview dialog checkbox for persisting manually
RHEAGROUP/CDP4-IME-Community-Edition pull request #718
Opened 2021-01-26 15:22 UTC by adrianchivu

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [ ] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

2021-01-27 11:10 UTC, lxatrhea approved these changes
I think we should get used to the fact that we should update headers to 2021.

2021-01-27 15:35 UTC, cozminvelciu requested changes
Will review after [parent PR](#684) is merged, as for now the diff is inconclusive. Being forced into sequential reviews and merges (instead of handling each issue separately) is one of the disadvantages of having multiple branches based on one another.

2021-01-28 13:23 UTC, cozminvelciu requested changes

2021-01-28 13:23 UTC, cozminvelciu commented on CDP4CrossViewEditor/ViewModels/WorkbookSelectionDialogResult.cs
> +        ///
Missing XML docs.

2021-01-28 13:23 UTC, cozminvelciu commented on CDP4CrossViewEditor/Views/CrossViewDialog.xaml
> +            <dxlc:LayoutControl View="Group"
One thing I suggest we do is move the checkbox and the text to the bottom of the dialog, and align it to the right, so it jumps out more when clicking OK / Cancel. Where it is now (upper left) makes it very easy to ignore/disregard.

2021-01-28 13:24 UTC, cozminvelciu commented on CDP4CrossViewEditor/Views/CrossViewDialog.xaml
> +            <dxlc:LayoutControl View="Group"
I'm not saying this is the right way, just a suggestion that might be worth implementing _if_ you agree.

2021-01-28 15:26 UTC, cozminvelciu approved these changes

2021-01-28 15:27 UTC, merged