[WIP] implement model paths fixes #757
RHEAGROUP/CDP4-IME-Community-Edition pull request #758
Opened 2021-02-25 13:44 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
 implement model paths

2021-02-25 15:33 UTC, samatrhea requested changes

2021-02-25 15:33 UTC, samatrhea commented on CDP4ReferenceDataMapper/Managers/DataSourceManager.cs
> +            var newActualFiniteStates = this.actualFiniteStateList.ActualState.Except(this.Columns.OfType<ActualStateDataGridColumn>().Select(x => x.ActualFiniteState)).OrderBy(x => x.ShortName).ToLi
there is an ordering defined for actual finite states which i think is implemented in `CDP4Common.Comparers.ActualFiniteStateComparer`

2021-02-26 14:11 UTC, samatrhea approved these changes

2021-03-02 13:09 UTC, alexatrhea approved these changes

2021-03-10 08:33 UTC, merged